
name: Uvicorn Image Builder

# Publish on new pushed, and build on Monday Morning (UTC) regardless.
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**/README.md'
      - 'templates/**'
  workflow_dispatch:
  schedule:
    - cron:  '10 0 * * *'


jobs:
  Uvicorn-Builder:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_versions: ["3.10", "3.11"] 
        package_versions: ["0.23.2"]
        target_base: ["slim"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: "Create and Push Image"
        uses: multi-py/action-python-image-builder@v1
        timeout-minutes: 45
        with:
          package: "uvicorn[standard]"
          package_latest_version: "0.23.2"
          maintainer: "Filippo Roggi <zzkw35@gmail.com>"
          python_version: ${{ matrix.python_versions }}
          package_version: ${{ matrix.package_versions }}
          target_base: ${{ matrix.target_base }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: "${{ github.workspace }}/dockerfile"
          docker_build_path: "${{ github.workspace }}/"
